[SystemSettings]

; VIEW DISTANCE / POP-IN
r.ViewDistanceScale=1.18
r.HLOD=1
r.HZBOcclusion=1
r.StaticMeshLODDistanceScale=0.80
foliage.LODDistanceScale=1.20
grass.CullDistanceScale=1.10

; TEXTURE STREAMING (8GB VRAM)
r.Streaming.LimitPoolSizeToVRAM=1
r.Streaming.PoolSize=5632
r.Streaming.MaxTempMemoryAllowed=256

; SHADOW
r.Shadow.DistanceScale=1.05
r.ContactShadows=0

; POST PROCESS
r.MotionBlurQuality=0
r.MotionBlur.Amount=0
r.DefaultFeature.MotionBlur=0
r.SceneColorFringeQuality=0
r.DepthOfFieldQuality=0

; ANISOTROPY
r.MaxAnisotropy=16

; TAA / DLSS
r.TemporalAACurrentFrameWeight=0.2
r.TemporalAASamples=12
r.TemporalAAFilterSize=1.0
r.NGX.DLSS.Sharpness=0.18
r.NGX.DLSS.EnableAutoExposure=1

; STABILITY
r.OneFrameThreadLag=1

; CPU / GAME THREAD
r.GTSyncType=0

; GARBAGE COLLECTION
gc.TimeBetweenPurgingPendingKillObjects=60

; NETWORK
net.MaxRPCPerNetUpdate=64
net.MaxPacketHandlerTime=0.02

; FOLIAGE CPU CULL
foliage.MaxTrianglesToRender=100000000

; ASYNC LOADING
s.AsyncLoadingThreadEnabled=1
s.LevelStreamingActorsUpdateTimeLimit=5.0
